[@ww.textfield labelKey="veracodeupload.api_username" name="api_username" required='true'/]
[@ww.textfield labelKey="veracodeupload.api_password" name="api_password" required='true'/]
[@ww.textfield labelKey="veracodeupload.app_id" name="app_id" required='true'/]
[@ww.textfield labelKey="veracodeupload.app_platform" name="app_platform" required='true'/]
[@ww.textfield labelKey="veracodeupload.build_id" name="build_id" required='true'/]
[@ww.textfield labelKey="veracodeupload.source_file" name="source_file" required='true'/]